export type DbEvent = {
  eventName?: string;
  eventType?: string;
  startDate?: string;
  endDate?: string;
  signupStart?: string;
  signupEnd?: string;
  locationArea?: string;
  locationName?: string;
  iconUrl?: string;
  genre?: string[];
  cost?: string;
  ageLimit?: string;
  beginnerFriendly?: boolean;
  eventFull?: boolean;
  invitationOnly?: boolean;
  languageFree?: boolean;
  storyDescription?: string;
  infoDescription?: string;
  links?: string[];
};
